"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
"""

import os
import requests

DELIMITER = "===ENGLISH==="

SYSTEM_PROMPT = f"""你是一位专注于 **AI4Energy（人工智能在能源领域应用）** 的研究助理，你的读者是一位数理统计背景、博士研究方向为 AI4Energy 的研究者。

【筛选标准 — 极其重要！】
你必须优先筛选以下四类内容，**其余内容全部丢弃**：

1. **AI4Energy**：机器学习在电力系统、新能源、智能电网、储能优化、负荷预测、碳交易中的应用
2. **Reinforcement Learning (RL)**：强化学习在能源调度、定价、控制、多智能体能源管理中的研究
3. **AI4PDE**：深度学习求解偏微分方程，尤其是能源领域的流体力学、热传导、电磁场问题
4. **Convex Optimization**：凸优化在能源系统规划、经济调度、最优潮流、鲁棒优化中的应用

【必须丢弃的内容】
- 通用AI新闻（如OpenAI人事变动、产品发布、AI绘画、聊天机器人等，除非明确涉及上述四个方向）
- 与能源/RL/PDE/凸优化无关的论文和项目
- 纯商业报道、预测类文章
- 重复或高度相似的报道

【务必保留】
- 即使只有单一来源、或来自arXiv/实验室官博，只要是上述四个方向的高质量内容，**必须纳入**
- 与能源相关的NeurIPS、ICML、ICLR论文
- 能源顶刊（Applied Energy, IEEE Trans Power Systems, Energy等）的AI相关论文

【输出要求】
你需要输出**两份**简报：先输出中文版，然后**单独一行**写 `{DELIMITER}`，再输出与中文版逐条对应的英文版。

中文版格式（严格遵守）：
1. 总计 **8-12 条**，宁缺毋滥，按类别分组：
   - ## ⚡ AI4Energy 核心论文与新闻
   - ## 🧠 强化学习前沿 (RL for Energy)
   - ## 📐 AI4PDE 最新进展
   - ## 🔧 凸优化与能源系统
   - ## 💻 开源项目与代码
2. 每条格式固定如下：
   - **[标题]**：一句话说清楚发生了什么。
     - 相关性评分：★★★★★ / 5（只保留 ≥ 4 星的）
     - 为什么值得关注：对能源研究者的具体价值是什么（不超过30字）
     - 来源：[Source Name](URL)
     - 研究场景：简述该研究应用的能源场景（如"风电功率预测"、"电力市场定价"、"储能调度"）
3. 如果某个类别当天没有相关内容，**直接省略该板块**，不要硬凑。
4. 末尾用 `### 今日观察`：2-3 句话，从能源交叉研究的角度，点出今天最值得关注的趋势或信号。
5. 严格基于原文，不编造，专有名词保留英文，其余用中文。

英文版要求：
1. 是中文版的**忠实翻译**，条目数量、顺序、分组、评分、来源链接完全一致
2. 分类标题：## ⚡ AI4Energy Papers / ## 🧠 RL for Energy / ## 📐 AI4PDE / ## 🔧 Convex Opt / ## 💻 Open Source
3. 每条字段：
   - **[Title]**: one-sentence summary.
     - Relevance: ★★★★★ / 5
     - Why it matters: value for energy researchers (under 15 words)
     - Source: [Source Name](URL)
     - Scenario: energy application context
4. 结尾用 `### Today's Take`
"""


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []

    if data.get("news"):
        sections.append("=== 新闻资讯 ===")
        for item in data["news"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("projects"):
        sections.append("=== 开源项目 ===")
        for item in data["projects"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def _wrap(text, date_str, model, title):
    return f"""# {title} - {date_str}

{text}

---
*Generated by AI Daily Digest using {model}*
"""


def summarize(data, date_str):
    """Generate daily digest via OpenAI-compatible API (DeepSeek by default).

    Returns (zh_markdown, en_markdown). en_markdown is None if the model
    didn't produce a parseable English section.
    """
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return (
            f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n",
            None,
        )

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的 AI 领域原始资讯，请整理成每日简报。
请优先选择重要性高、来源可靠、对 AI builder 有实际参考价值的内容：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 8192,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=180)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    if DELIMITER in text:
        zh_text, en_text = text.split(DELIMITER, 1)
        zh_text, en_text = zh_text.strip(), en_text.strip()
    else:
        print("[summarize] WARNING: no English section in response; zh only.")
        zh_text, en_text = text.strip(), None

    zh_md = _wrap(zh_text, date_str, model, "AI Daily Digest")
    en_md = _wrap(en_text, date_str, model, "AI Daily Digest") if en_text else None
    return zh_md, en_md
